language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: bionic
env:
  global:
    - DEPOPTS="*"
    - TESTS=true
    - DISTRO=ubuntu-18.04
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.03 PACKAGE="zmq"       PINS="zmq:."
  - os: linux
    env: OCAML_VERSION=4.04 PACKAGE="zmq-async" PINS="zmq:. zmq-async:."
  - os: linux
    env: OCAML_VERSION=4.03 PACKAGE="zmq-lwt"   PINS="zmq:. zmq-lwt:."
  - os: linux
    env: OCAML_VERSION=4.08 PACKAGE="zmq"       PINS="zmq:."
  - os: linux
    env: OCAML_VERSION=4.08 PACKAGE="zmq-async" PINS="zmq:. zmq-async:."
  - os: linux
    env: OCAML_VERSION=4.08 PACKAGE="zmq-lwt"   PINS="zmq:. zmq-lwt:."
  - os: linux
    env: OCAML_VERSION=4.09 PACKAGE="zmq"       PINS="zmq:."
  - os: linux
    env: OCAML_VERSION=4.09 PACKAGE="zmq-async" PINS="zmq:. zmq-async:."
  - os: linux
    env: OCAML_VERSION=4.09 PACKAGE="zmq-lwt"   PINS="zmq:. zmq-lwt:."
  - os: osx
    env: OCAML_VERSION=4.09 PACKAGE="zmq"       PINS="zmq:."
