#!/bin/sh
# Designed for the Travis CI build environment. See .travis.yml

set -ex

# poor man's caching; download the existing layers for ocaml/rwo
# this will avoid having to download and install the dependencies
docker pull mseri/owl_tutorials:latest

cd $TRAVIS_BUILD_DIR
echo Build started at `date`
docker build --cache-from mseri/owl_tutorials:latest -t mseri/owl_tutorials .
echo Build completed at `date`
#echo Using Hub build due to a Travis build hanging
#docker pull mseri/owl_tutorials
docker run --name temp-container mseri/owl_tutorials /bin/true
docker cp temp-container:/home/opam/src/_build/default/static $TRAVIS_BUILD_DIR/site
find $TRAVIS_BUILD_DIR/site
